### ISSUE TITLE
License is needed

### ISSUE THREAD

**Issue by daflame76** [npcook/terminal#1]
I searched through your code for a clear license definition, but I couldn't find one.  Do you have a clear definition somewhere and I just can't find it?  It would be helpful to define the license in a file in the root of your repository or at least a readme somewhere.

Without a clear license I can't use your code at all since I can't be certain it doesn't conflict with corporate legal or moral policies.

**Comment by daflame76** [comment]
@npcook I would appreciate it if you could identify your license.  Even if only in this issue or I could offer a pull request with the actual license if you give me the license type.

**Comment by npcook** [comment]
Hi, sorry for the delay, I've been pretty busy the past couple weeks. I've released this under the MIT license.

**Comment by jcoder76** [comment]
License was added.
